<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Ivan Josipovic</Authors>
    <Description>Converts Composite Resource Definition Yaml files to Models</Description>
    <PackageTags>Crossplane Convert CompositeResourceDefinition Yaml Model </PackageTags>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RepositoryUrl>https://github.com/IvanJosipovic/function-sdk-csharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>false</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesCRDModelGen.Base" Version="1.6.14" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet.System.Text.Json" Version="1.9.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <!-- Generator dependencies -->
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <PropertyGroup>
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="GetDependencyTargetPaths" AfterTargets="ResolvePackageDependenciesForBuild">
    <ItemGroup>
    <DllDependencies Include="@(ResolvedCompileFileDefinitions->'%(FullPath)')" Condition="$([System.String]::Equals('%(ResolvedCompileFileDefinitions.Extension)', '.dll')) and ! $([System.String]::Copy('%(ResolvedCompileFileDefinitions.Filename)').StartsWith('Microsoft.CodeAnalysis'))" />
      <TargetPathWithTargetPlatformMoniker Include="@(DllDependencies)" IncludeRuntimeDependency="false" />
      <None Include="@(DllDependencies)" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
  </Target>
</Project>